name: "E2E tests"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  EtherpadWithLinux:
    name: Etherpad with Plugins
    runs-on: ubuntu-latest
    services:
      etherpad:
        image: etherpad/etherpad:${{ matrix.version }}
        env:
          ETHERPAD_PLUGINS: "ep_align ep_headings2 ep_table_of_contents ep_font_size ep_spellcheck sp_markdown"
        ports:
          - 9001:9001

    strategy:
      matrix:
        version: ["latest", "1.9.0"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Scan etherpad instance
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: bin/console.php ether:scan etherpad:9001
          contains: "Package version: 1.9.7"
          expected_result: PASSED